name: Notify Success After Failure

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  notify-success:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.event_name == 'push' && github.event.before != '0000000000000000000000000000000000000000'

    steps:
      - name: Send Discord Message
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_TEST_FAILS }}
          status: ${{job.status}}
          content: "The tests succeeding again."
          title: "Run Tests"
          description: "Runs all of the tests that are defined in the package.json"
          #image: ${{secrets.EMBED_IMAGE}}
          #avatar_url: ${{secrets.AVATAR_URL}}
          url: "https://github.com/Trickje/NAS/actions/workflows/runtests.yml"
          username: "Github.com/Trickje/NAS: Run Tests"
          color: 0x00ff00
          message: "Tests passed in the GitHub Actions workflow after a previous failure."
